### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by EricsNotion** [lwitzani/daysUntilBirthday#2]
Hi all,
I had installed this Script on my phone where I am using outlook as a data source. As you described, when using showAll parameter the script have to work anyway. Nope, unfortunately not.
The Error is on line 110:45: ReferenceError: Can’t find variable: getFixedDate

Regards, Eric

**Comment by lwitzani** [comment]
Hi,
how did you install the script? By hand (marking everything, copying and pasting it in Scriptable) or using Scriptdu.de ?
My hot guess is you did it by hand and missed the part at the very bottom of the file https://raw.githubusercontent.com/lwitzani/daysUntilBirthday/main/daysUntilBirthdayWidget.js

The last function at the bottom is the function called getFixedDate. Do you have that function in your script? If yes, then i have no idea what the problem could be since "Can’t find variable: getFixedDate" exactly states that it can't find getFixedDate ...

**Comment by lwitzani** [comment]
Also i am not sure how this script behaves, if the contacts are in/from outlook. The contacts should be available in the iphone app "Contacts". If i remember right, then all contact container are checked. So as long as your contacts are also in the ios Contacts app, it should work using showAllContacts = true ;)

**Comment by lwitzani** [comment]
Were you able to fix your problem and get it running ?

**Comment by EricsNotion** [comment]
Hey, sorry missed to give you an update. It was a layer 8 issue. I just missed a couple rows at the end of the script. This happend because of copy paste on iPad didn't catch the whole script. Sorry
